package workflow

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/charmbracelet/crush/internal/skills"
	"gopkg.in/yaml.v3"
)

const (
	contextDirName = ".crush/context"
	activeFileName = "active.yaml"
)

var workflowUpdateMu sync.Mutex

// ActiveState points at the workflow context currently selected for a project.
// The file is generated by workflow commands; developers should not need to
// edit it by hand.
type ActiveState struct {
	Version        int               `yaml:"version"`
	ActiveContext  string            `yaml:"active_context"`
	ActiveSkill    string            `yaml:"active_skill,omitempty"`
	WorkerSessions map[string]string `yaml:"worker_sessions,omitempty"`
}

// ResolvedContext is the skill-scoped projection attached to an agent prompt.
type ResolvedContext struct {
	Content      []byte
	SourcePath   string
	RelativePath string
}

// SetActiveContext marks filename as the workflow context to use for future
// prompts in projectRoot. filename must name a file inside .crush/context.
func SetActiveContext(projectRoot, filename string) error {
	if filename == "" || filepath.Base(filename) != filename || filename == activeFileName {
		return fmt.Errorf("invalid workflow context filename %q", filename)
	}

	dir := filepath.Join(projectRoot, filepath.FromSlash(contextDirName))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create workflow context directory: %w", err)
	}

	statePath := filepath.Join(dir, activeFileName)
	state := ActiveState{Version: 1}
	if data, err := os.ReadFile(statePath); err == nil {
		_ = yaml.Unmarshal(data, &state)
	}
	state.Version = 1
	if state.ActiveContext != "" && state.ActiveContext != filename {
		// A different issue/work item must never inherit worker sessions from
		// the previously active context.
		state.ActiveSkill = ""
		state.WorkerSessions = nil
	}
	state.ActiveContext = filename

	data, err := yaml.Marshal(state)
	if err != nil {
		return fmt.Errorf("marshal active workflow state: %w", err)
	}
	return writeFileAtomic(statePath, data, 0o644)
}

// LoadActiveState returns the project workflow pointer and worker-session map.
func LoadActiveState(projectRoot string) (ActiveState, bool, error) {
	statePath := filepath.Join(projectRoot, filepath.FromSlash(contextDirName), activeFileName)
	data, err := os.ReadFile(statePath)
	if errors.Is(err, os.ErrNotExist) {
		return ActiveState{}, false, nil
	}
	if err != nil {
		return ActiveState{}, false, err
	}
	var state ActiveState
	if err := yaml.Unmarshal(data, &state); err != nil {
		return ActiveState{}, false, fmt.Errorf("parse %s: %w", statePath, err)
	}
	if state.WorkerSessions == nil {
		state.WorkerSessions = map[string]string{}
	}
	return state, true, nil
}

// SetActiveSkill persists the selected worker without changing its session.
func SetActiveSkill(projectRoot, skillName string) error {
	state, ok, err := LoadActiveState(projectRoot)
	if err != nil {
		return err
	}
	if !ok {
		return nil
	}
	state.ActiveSkill = strings.TrimSpace(skillName)
	return saveActiveState(projectRoot, state)
}

// WorkerSession returns the Crush session dedicated to skillName for the
// currently active workflow.
func WorkerSession(projectRoot, skillName string) (string, bool, error) {
	state, ok, err := LoadActiveState(projectRoot)
	if err != nil || !ok {
		return "", false, err
	}
	id := state.WorkerSessions[strings.TrimSpace(skillName)]
	return id, id != "", nil
}

// SetWorkerSession persists a worker -> Crush session mapping.
func SetWorkerSession(projectRoot, skillName, sessionID string) error {
	state, ok, err := LoadActiveState(projectRoot)
	if err != nil {
		return err
	}
	if !ok {
		return nil
	}
	if state.WorkerSessions == nil {
		state.WorkerSessions = map[string]string{}
	}
	skillName = strings.TrimSpace(skillName)
	if skillName == "" {
		return fmt.Errorf("worker skill name is empty")
	}
	if strings.TrimSpace(sessionID) == "" {
		delete(state.WorkerSessions, skillName)
	} else {
		state.WorkerSessions[skillName] = strings.TrimSpace(sessionID)
	}
	state.ActiveSkill = skillName
	return saveActiveState(projectRoot, state)
}

func saveActiveState(projectRoot string, state ActiveState) error {
	state.Version = 1
	statePath := filepath.Join(projectRoot, filepath.FromSlash(contextDirName), activeFileName)
	data, err := yaml.Marshal(state)
	if err != nil {
		return fmt.Errorf("marshal active workflow state: %w", err)
	}
	return writeFileAtomic(statePath, data, 0o644)
}

// WorkerForSession resolves the active workflow worker owning sessionID.
// Non-workflow sessions return ok=false without error.
func WorkerForSession(projectRoot, sessionID string) (worker string, ok bool, err error) {
	sessionID = strings.TrimSpace(sessionID)
	if sessionID == "" {
		return "", false, nil
	}
	state, active, err := LoadActiveState(projectRoot)
	if err != nil || !active {
		return "", false, err
	}
	for name, id := range state.WorkerSessions {
		if strings.TrimSpace(id) != sessionID {
			continue
		}
		if worker != "" && !strings.EqualFold(worker, name) {
			return "", false, fmt.Errorf("session %q is mapped to multiple workflow workers", sessionID)
		}
		worker = name
	}
	if worker == "" {
		return "", false, nil
	}
	return worker, true, nil
}

// UpdateWorkflowMemory persists durable workflow data for the worker session
// identified by sessionID. The caller cannot choose the workflow file or worker
// name: both are derived from active.yaml. Most fields are merged into
// workers.<skill>; the reserved top-level findings field updates the shared
// workflow finding lifecycle. Nested worker maps merge recursively; scalar
// values and lists replace previous values.
func UpdateWorkflowMemory(projectRoot, sessionID string, data map[string]any) (string, string, error) {
	sessionID = strings.TrimSpace(sessionID)
	if sessionID == "" {
		return "", "", fmt.Errorf("workflow update requires a session ID")
	}
	if len(data) == 0 {
		return "", "", fmt.Errorf("workflow update data is empty")
	}

	workflowUpdateMu.Lock()
	defer workflowUpdateMu.Unlock()

	worker, ok, err := WorkerForSession(projectRoot, sessionID)
	if err != nil {
		return "", "", err
	}
	if !ok {
		return "", "", fmt.Errorf("session %q is not mapped to an active workflow worker", sessionID)
	}

	sourcePath, relativePath, ok, err := findActiveContext(projectRoot)
	if err != nil {
		return "", "", err
	}
	if !ok {
		return "", "", fmt.Errorf("no active workflow context")
	}
	doc, err := readYAMLMap(sourcePath)
	if err != nil {
		return "", "", fmt.Errorf("read active workflow context: %w", err)
	}

	workerData := make(map[string]any, len(data))
	for key, value := range data {
		if key == "findings" {
			if err := mergeWorkflowFindings(doc, worker, value); err != nil {
				return "", "", err
			}
			continue
		}
		workerData[key] = value
	}

	if len(workerData) > 0 {
		workersValue, exists := doc["workers"]
		workers, ok := workersValue.(map[string]any)
		if exists && !ok {
			return "", "", fmt.Errorf("workflow workers section is not an object")
		}
		if !exists {
			workers = map[string]any{}
			doc["workers"] = workers
		}
		existingValue, exists := workers[worker]
		existing, ok := existingValue.(map[string]any)
		if exists && !ok {
			return "", "", fmt.Errorf("workflow worker %q state is not an object", worker)
		}
		if !exists {
			existing = map[string]any{}
		}
		workers[worker] = mergeWorkerMemory(existing, workerData)
	}

	encoded, err := yaml.Marshal(doc)
	if err != nil {
		return "", "", fmt.Errorf("marshal active workflow context: %w", err)
	}
	if err := writeFileAtomic(sourcePath, encoded, 0o644); err != nil {
		return "", "", fmt.Errorf("write active workflow context: %w", err)
	}
	return worker, relativePath, nil
}

// ResolveActive projects the active workflow YAML according to the active
// skill. With no explicit context frontmatter, the convention is:
//
//	shared + open findings + workers.<skill>
//
// Explicit context.include paths are additive. writable paths are included in
// projection metadata so the skill knows which parts of the source document it
// owns. This is context minimization, not a filesystem security boundary.
func ResolveActive(projectRoot, skillName string, policy skills.ContextPolicy) (ResolvedContext, bool, error) {
	sourcePath, relativePath, ok, err := findActiveContext(projectRoot)
	if err != nil || !ok {
		return ResolvedContext{}, ok, err
	}

	doc, err := readYAMLMap(sourcePath)
	if err != nil {
		return ResolvedContext{}, false, fmt.Errorf("read active workflow context: %w", err)
	}

	shared := true
	if policy.Shared != nil {
		shared = *policy.Shared
	}
	ownWorker := true
	if policy.OwnWorker != nil {
		ownWorker = *policy.OwnWorker
	}

	include := make([]string, 0, len(policy.Include)+1)
	writable := make([]string, 0, len(policy.Writable)+2)
	if ownWorker && skillName != "" {
		ownPath := "workers." + skillName
		include = append(include, ownPath)
		writable = append(writable, ownPath)
	}
	include = appendUnique(include, policy.Include...)
	writable = appendUnique(writable, policy.Writable...)
	writable = appendUnique(writable, "findings")

	projection := map[string]any{
		"workflow": map[string]any{
			"source": relativePath,
			"worker": skillName,
			"write":  writable,
			"rule":   durableMemoryRule,
		},
	}

	findings, err := openWorkflowFindings(doc["findings"])
	if err != nil {
		return ResolvedContext{}, false, err
	}
	if len(findings) > 0 {
		projection["findings"] = findings
	}

	if shared {
		if value, exists := doc["shared"]; exists {
			projection["shared"] = deepCopy(value)
		} else {
			projection["shared"] = map[string]any{}
		}
	}

	for _, path := range include {
		value, exists := getPath(doc, path)
		if !exists {
			value = map[string]any{}
		}
		setPath(projection, path, deepCopy(value))
	}

	content, err := yaml.Marshal(projection)
	if err != nil {
		return ResolvedContext{}, false, fmt.Errorf("marshal scoped workflow context: %w", err)
	}
	return ResolvedContext{Content: content, SourcePath: sourcePath, RelativePath: relativePath}, true, nil
}

const durableMemoryRule = "Before the final response, call workflow_update whenever this turn produced durable facts, findings, decisions, changes, test results, blockers, or working-set references. Reconcile open findings with the latest work: mark addressed findings resolved, obsolete findings superseded, and keep unresolved findings open. Findings are keyed by stable IDs; update an existing ID instead of creating a duplicate. Store only concise facts and file/symbol/range references, never full source or raw tool output."

const (
	findingStatusOpen       = "open"
	findingStatusResolved   = "resolved"
	findingStatusSuperseded = "superseded"
)

func mergeWorkflowFindings(doc map[string]any, worker string, value any) error {
	updates, ok := value.(map[string]any)
	if !ok {
		return fmt.Errorf("workflow findings must be an object keyed by finding ID")
	}

	existingValue := doc["findings"]
	existing, ok := existingValue.(map[string]any)
	if existingValue != nil && !ok {
		return fmt.Errorf("workflow findings section is not an object")
	}
	if existing == nil {
		existing = map[string]any{}
	}

	normalized := make(map[string]any, len(updates))
	for id, raw := range updates {
		id = strings.TrimSpace(id)
		if id == "" {
			return fmt.Errorf("workflow finding ID is empty")
		}
		finding, ok := raw.(map[string]any)
		if !ok {
			return fmt.Errorf("workflow finding %q must be an object", id)
		}
		finding = cloneMap(finding)
		if rawStatus, exists := finding["status"]; exists {
			status, ok := rawStatus.(string)
			if !ok || !validFindingStatus(strings.TrimSpace(status)) {
				return fmt.Errorf("invalid workflow finding status %q", rawStatus)
			}
			finding["status"] = strings.TrimSpace(status)
		}
		if _, exists := existing[id]; !exists {
			if _, exists := finding["status"]; !exists {
				finding["status"] = findingStatusOpen
			}
			if _, exists := finding["source"]; !exists {
				finding["source"] = worker
			}
		}
		normalized[id] = finding
	}

	doc["findings"] = mergeMaps(existing, normalized)
	return nil
}

func openWorkflowFindings(value any) (map[string]any, error) {
	if value == nil {
		return nil, nil
	}
	findings, ok := value.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("workflow findings section is not an object")
	}

	open := make(map[string]any)
	for id, raw := range findings {
		finding, ok := raw.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("workflow finding %q is not an object", id)
		}
		status, _ := finding["status"].(string)
		status = strings.TrimSpace(status)
		if status == "" || status == findingStatusOpen {
			open[id] = deepCopy(finding)
		}
	}
	if len(open) == 0 {
		return nil, nil
	}
	return open, nil
}

func validFindingStatus(status string) bool {
	switch status {
	case findingStatusOpen, findingStatusResolved, findingStatusSuperseded:
		return true
	default:
		return false
	}
}

func cloneMap(value map[string]any) map[string]any {
	copy, ok := deepCopy(value).(map[string]any)
	if !ok {
		return map[string]any{}
	}
	return copy
}

func findActiveContext(projectRoot string) (sourcePath, relativePath string, ok bool, err error) {
	dir := filepath.Join(projectRoot, filepath.FromSlash(contextDirName))
	statePath := filepath.Join(dir, activeFileName)
	if data, readErr := os.ReadFile(statePath); readErr == nil {
		var state ActiveState
		if err := yaml.Unmarshal(data, &state); err != nil {
			return "", "", false, fmt.Errorf("parse %s: %w", statePath, err)
		}
		if state.ActiveContext == "" {
			return "", "", false, fmt.Errorf("%s has no active_context", statePath)
		}
		if filepath.Base(state.ActiveContext) != state.ActiveContext || state.ActiveContext == activeFileName {
			return "", "", false, fmt.Errorf("invalid active_context %q", state.ActiveContext)
		}
		path := filepath.Join(dir, state.ActiveContext)
		if _, err := os.Stat(path); err != nil {
			return "", "", false, fmt.Errorf("active workflow context %q: %w", path, err)
		}
		return path, filepath.ToSlash(filepath.Join(contextDirName, state.ActiveContext)), true, nil
	} else if !errors.Is(readErr, os.ErrNotExist) {
		return "", "", false, readErr
	}

	// active.yaml is the only selector. Local workflows are created
	// automatically and issue/work commands activate their context.
	return "", "", false, nil
}

func readYAMLMap(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	if doc == nil {
		doc = map[string]any{}
	}
	return doc, nil
}

func mergeWorkerMemory(existing, updates map[string]any) map[string]any {
	merged := mergeMaps(existing, updates)
	if checkpoint, exists := updates["checkpoint"]; exists {
		merged["checkpoint"] = deepCopy(checkpoint)
	}
	return merged
}

func mergeMaps(dst, src map[string]any) map[string]any {
	out := make(map[string]any, len(dst)+len(src))
	for key, value := range dst {
		out[key] = deepCopy(value)
	}
	for key, value := range src {
		srcMap, srcIsMap := value.(map[string]any)
		dstMap, dstIsMap := out[key].(map[string]any)
		if srcIsMap && dstIsMap {
			out[key] = mergeMaps(dstMap, srcMap)
			continue
		}
		out[key] = deepCopy(value)
	}
	return out
}

func getPath(root map[string]any, path string) (any, bool) {
	parts := strings.Split(strings.Trim(path, "."), ".")
	if len(parts) == 0 || parts[0] == "" {
		return nil, false
	}
	var current any = root
	for _, part := range parts {
		m, ok := current.(map[string]any)
		if !ok {
			return nil, false
		}
		current, ok = m[part]
		if !ok {
			return nil, false
		}
	}
	return current, true
}

func setPath(root map[string]any, path string, value any) {
	parts := strings.Split(strings.Trim(path, "."), ".")
	if len(parts) == 0 || parts[0] == "" {
		return
	}
	current := root
	for _, part := range parts[:len(parts)-1] {
		next, ok := current[part].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[part] = next
		}
		current = next
	}
	current[parts[len(parts)-1]] = value
}

func appendUnique(dst []string, values ...string) []string {
	seen := make(map[string]struct{}, len(dst)+len(values))
	for _, value := range dst {
		seen[value] = struct{}{}
	}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		dst = append(dst, value)
	}
	return dst
}

func deepCopy(value any) any {
	data, err := yaml.Marshal(value)
	if err != nil {
		return value
	}
	var copy any
	if err := yaml.Unmarshal(data, &copy); err != nil {
		return value
	}
	return copy
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".crush-workflow-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}
