package workflow

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/crush/internal/skills"
	"gopkg.in/yaml.v3"
)

const (
	contextDirName = ".crush/context"
	activeFileName = "active.yaml"
)

// ActiveState points at the workflow context currently selected for a project.
// The file is generated by workflow commands; developers should not need to
// edit it by hand.
type ActiveState struct {
	Version       int    `yaml:"version"`
	ActiveContext string `yaml:"active_context"`
	ActiveSkill   string `yaml:"active_skill,omitempty"`
}

// ResolvedContext is the skill-scoped projection attached to an agent prompt.
type ResolvedContext struct {
	Content      []byte
	SourcePath   string
	RelativePath string
}

// SetActiveContext marks filename as the workflow context to use for future
// prompts in projectRoot. filename must name a file inside .crush/context.
func SetActiveContext(projectRoot, filename string) error {
	if filename == "" || filepath.Base(filename) != filename || filename == activeFileName {
		return fmt.Errorf("invalid workflow context filename %q", filename)
	}

	dir := filepath.Join(projectRoot, filepath.FromSlash(contextDirName))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create workflow context directory: %w", err)
	}

	statePath := filepath.Join(dir, activeFileName)
	state := ActiveState{Version: 1}
	if data, err := os.ReadFile(statePath); err == nil {
		_ = yaml.Unmarshal(data, &state)
	}
	state.Version = 1
	state.ActiveContext = filename

	data, err := yaml.Marshal(state)
	if err != nil {
		return fmt.Errorf("marshal active workflow state: %w", err)
	}
	return writeFileAtomic(statePath, data, 0o644)
}

// ResolveActive projects the active workflow YAML according to the active
// skill. With no explicit context frontmatter, the convention is:
//
//	shared + workers.<skill>
//
// Explicit context.include paths are additive. writable paths are included in
// projection metadata so the skill knows which parts of the source document it
// owns. This is context minimization, not a filesystem security boundary.
func ResolveActive(projectRoot, skillName string, policy skills.ContextPolicy) (ResolvedContext, bool, error) {
	sourcePath, relativePath, ok, err := findActiveContext(projectRoot)
	if err != nil || !ok {
		return ResolvedContext{}, ok, err
	}

	doc, err := readYAMLMap(sourcePath)
	if err != nil {
		return ResolvedContext{}, false, fmt.Errorf("read active workflow context: %w", err)
	}

	shared := true
	if policy.Shared != nil {
		shared = *policy.Shared
	}
	ownWorker := true
	if policy.OwnWorker != nil {
		ownWorker = *policy.OwnWorker
	}

	include := make([]string, 0, len(policy.Include)+1)
	writable := make([]string, 0, len(policy.Writable)+1)
	if ownWorker && skillName != "" {
		ownPath := "workers." + skillName
		include = append(include, ownPath)
		writable = append(writable, ownPath)
	}
	include = appendUnique(include, policy.Include...)
	writable = appendUnique(writable, policy.Writable...)

	projection := map[string]any{
		"workflow": map[string]any{
			"source_file":   relativePath,
			"active_worker": skillName,
			"writable":      writable,
			"note":          "This is a scoped projection. Update only writable paths in source_file; do not replace unrelated workflow state.",
		},
	}

	if shared {
		if value, exists := doc["shared"]; exists {
			projection["shared"] = deepCopy(value)
		} else {
			projection["shared"] = map[string]any{}
		}
	}

	for _, path := range include {
		value, exists := getPath(doc, path)
		if !exists {
			value = map[string]any{}
		}
		setPath(projection, path, deepCopy(value))
	}

	content, err := yaml.Marshal(projection)
	if err != nil {
		return ResolvedContext{}, false, fmt.Errorf("marshal scoped workflow context: %w", err)
	}
	return ResolvedContext{Content: content, SourcePath: sourcePath, RelativePath: relativePath}, true, nil
}

func findActiveContext(projectRoot string) (sourcePath, relativePath string, ok bool, err error) {
	dir := filepath.Join(projectRoot, filepath.FromSlash(contextDirName))
	statePath := filepath.Join(dir, activeFileName)
	if data, readErr := os.ReadFile(statePath); readErr == nil {
		var state ActiveState
		if err := yaml.Unmarshal(data, &state); err != nil {
			return "", "", false, fmt.Errorf("parse %s: %w", statePath, err)
		}
		if state.ActiveContext == "" {
			return "", "", false, fmt.Errorf("%s has no active_context", statePath)
		}
		if filepath.Base(state.ActiveContext) != state.ActiveContext || state.ActiveContext == activeFileName {
			return "", "", false, fmt.Errorf("invalid active_context %q", state.ActiveContext)
		}
		path := filepath.Join(dir, state.ActiveContext)
		if _, err := os.Stat(path); err != nil {
			return "", "", false, fmt.Errorf("active workflow context %q: %w", path, err)
		}
		return path, filepath.ToSlash(filepath.Join(contextDirName, state.ActiveContext)), true, nil
	} else if !errors.Is(readErr, os.ErrNotExist) {
		return "", "", false, readErr
	}

	// Convenience fallback for projects with exactly one imported issue.
	matches, globErr := filepath.Glob(filepath.Join(dir, "issue-*.yaml"))
	if globErr != nil {
		return "", "", false, globErr
	}
	if len(matches) != 1 {
		return "", "", false, nil
	}
	return matches[0], filepath.ToSlash(filepath.Join(contextDirName, filepath.Base(matches[0]))), true, nil
}

func readYAMLMap(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	if doc == nil {
		doc = map[string]any{}
	}
	return doc, nil
}

func getPath(root map[string]any, path string) (any, bool) {
	parts := strings.Split(strings.Trim(path, "."), ".")
	if len(parts) == 0 || parts[0] == "" {
		return nil, false
	}
	var current any = root
	for _, part := range parts {
		m, ok := current.(map[string]any)
		if !ok {
			return nil, false
		}
		current, ok = m[part]
		if !ok {
			return nil, false
		}
	}
	return current, true
}

func setPath(root map[string]any, path string, value any) {
	parts := strings.Split(strings.Trim(path, "."), ".")
	if len(parts) == 0 || parts[0] == "" {
		return
	}
	current := root
	for _, part := range parts[:len(parts)-1] {
		next, ok := current[part].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[part] = next
		}
		current = next
	}
	current[parts[len(parts)-1]] = value
}

func appendUnique(dst []string, values ...string) []string {
	seen := make(map[string]struct{}, len(dst)+len(values))
	for _, value := range dst {
		seen[value] = struct{}{}
	}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		dst = append(dst, value)
	}
	return dst
}

func deepCopy(value any) any {
	data, err := yaml.Marshal(value)
	if err != nil {
		return value
	}
	var copy any
	if err := yaml.Unmarshal(data, &copy); err != nil {
		return value
	}
	return copy
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".crush-workflow-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}
